version: "3.9"
services:
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "${NGINX_PORT}:80"
        environment:
            NGINX_ENV_VAR: ${NGINX_ENV_VAR}
        container_name: ${NGINX_CONTAINER_NAME}
        volumes:
            - ./public:/var/www/public
            - ./nginx-config:/etc/nginx/conf.d
        networks:
            - app_network_local

 
networks:
  app_network_local:
    external: true